project:
  type: website
  resources:
    - "images/twitter-card.png"
    - "materials/*.pdf"
    - "data/*"
    - "lab.R"
  render:
    - "*.qmd"
    - "!materials"
    - "!README.Rmd"
  pre-render: zip.R

website:
  page-navigation: true
  title: "Tidy time series & forecasting in R"
  description: "Homepage for F4SG time series workshop at UM6P in 2024"
  site-url: "https://workshop.nectric.com.au/f4sg-um6p"
  
  repo-url: https://github.com/mitchelloharawild/workshop-f4sg-um6p
  repo-actions: [edit, issue]

  # opengraph: true
  twitter-card:
    creator: "@mitchoharawild"
    image: "/images/twitter-card.png"

  favicon: "/images/fable.svg"

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    right: "&copy; Copyright 2024, Mitchell O'Hara-Wild"
    background: "#426D98"

  navbar:
    background: "#426D98"
    pinned: true
    align: center
    right:
      - icon: download
        text: Downloads
        menu: 
          - text: Everything
            href: 'https://github.com/mitchelloharawild/workshop-f4sg-um6p/archive/refs/heads/main.zip'
          - text: Slides
            href: 'slides.zip'
          # - text: Lab sessions
          #   href: 'labs.zip'
      - icon: file-certificate
        href: license.qmd
      - icon: github
        href: https://github.com/mitchelloharawild/workshop-f4sg-um6p
    left:
      - text: Slides
        menu:
          - text: Time series data and manipulation
            href: materials/data/slides.qmd
          - text: Time series patterns and visualisation
            href: materials/graphics/slides.qmd
          - text: Transformations and decomposition
            href: materials/decomposition/slides.qmd
      - href: schedule.qmd

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Open Sans"
    include-after-body: plausible.html
